XXXXXXXXXXXXXXXXXX
XXXXXXXXXX XXXXXXX
XXXXXXXXXXXXXXXXXX

XXXXXXXXXX XXXX XXXXXXXXXX XXXXXX XXXXXXX XX XXXXXXXXXXX XXXXXXX XX
XXXX X XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX
XXXXXXXXXXXXXXXX XXXXXX XX XXXXXXXXX XXXXX XX XXXXXXXX XXXXXXXX XXX
XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXX

XXX XXXXXXXXXXX XXXXXX XX XXXXXXXX XXX XXX XX XXX XXXXXXXX XXXXXXX XXXX XXXXX
XXXXXXXXX XXXX XXXXXXXX

XX XXXXXXXXXXXXXX XXX XXX XXXXXXX XX XXXXXXX XXX XXXXXXXXX XXXXXXXXX
XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXX XXXX XXXXXXXX XXX XXXXXXXXXX XXXXXXX XXX XXXX XX XXXXXXXXX
XXXXXXXXXXXX XXX XXX XXXXXX XXXX XXXXXXXXX XXXXXXX XXX XXXXXXXXXXXXXXXXX
XXXXXXXXXXXX XX XXX XXX XX XXXXXXXXXXXX XX XXXXXXXXXXXXXXX

XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
XX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XX XXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXX

XX XXXXXXXXXXXXXXXXXXXX

XXXXXXXX X XXXXXXX XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX X XXXXXXXX XX XXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXX XX XXXXXX XXXXXXX
XXXXXXXXXXXXXXX

    X XXXXXXXX  XXX XXXXX
    X XXXX XXX XXXXX
    X XXXXXX XXXXXXXXX XXXXXXXX

XXX XXXXXXXX XXXX XXXX XX X XXXXXXXXX XX XXXXX XX XXX
XXXXXXXX XXXXXXXXX XXXXXXXXXXX XXX XXXXXXX XX XXX XXXXXX XXX XXXXXXXXXXXXXXXXXX
XXXXXXXX XX XXXXXXXXXXX XX XX XXX X XXXXXXXXX XXXXXXXXX XX XXXX XXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXX XXXXXX XXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXX X X
            XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
        X

XX XXX XXXX XX XXX XXXXXXX XXXXXX XXXXXXXXXXXXX XX XXXXXXX XXX XXX XXXXXX XXXX
XXXXXXXX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXX XXXXXXX XXX XXXXXXXXX XXXXX
XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
XXXXXXXXXX XX XXXXXXXX XX XXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX

XXXXXXXXX XXXX XXX XXXXXXXXX XXXXXXXX XXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
XX XXX XXXX XX XXX XXXXX XXXXXXXX XX XXXX XXXXXX XXX XXX XXXX XXXXXXX XXX
XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX XXXXXXX XXXXXXXX XXXXXXXXX
XXXXXXXXXXXXXXXXXXXX

XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX XXX XXXXXXXX
XXXXXXXXXXXXXXXXXXXXX

XX XXXXXXXXXX XXX XXXXXXXXX XXX XXX XXXXXX XXX XXX XXXXXXX XXX XXXXXXX
XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXX XXX XXXXXXX XXXXX XX XXX
XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXX XXX XXX XXXXXXXX
XXX XXXXXXXX XX XXXXXX X XXXXXXXXXXXXX XXXXXXX XXXXXXXX XXX XXXXX XXX XXXXXXXXX
XXX XX XXXXXXXX XXXX XXX XXX XXXXX XX XXX XXXXXXXXXXXX XXXXXX

    XXXXXXXXX XXXXXX XXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXX
    XXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXX
